* Book One: Kings Amlaib and Murchad 
** Act One: September and October 1066
  King Amlaíb of Mumu was a happy man, to put it mildly. He found himself in
  arms with the young lad Murchad next to him, the younger knight spinning
  his newlywed around as the dance continued. 
  
  "It's honestly hard to believe that we are fully wed now," the joyful blonde
  said with a chuckle.

  "I know," came the reply along with a stolen kiss. Not that the other man
  minded.

  "They will want us to have an heir somehow, whether through adoption or - "

  "We will figure that out when the time comes," Amlaíb replied.

  "Many of the vassals seem to be -"

  "We will get there when we get there. For now, let's just enjoy tonight."

  "Indeed. I feel so very blessed to have you by my side."

  "I do too." Both men laughed, and the dance continued.

*** September 19, 1066
    "They will expect you to sire an heir at some point, Amlaíb," the
    golden knight chuckled as he pulled the heavy furs around the
    two. Yes, the night had been a long one, good for relaxing and
    ignoring the stresses of the time as the two snuggled close. 

    "I know that, dear husband, and I have already been in talks with
    one of my courtiers - Bébin. I think we had some ale together
    during our wedding.¨ 
