* Book One: Kings Amlaíb and Murchad 
** Act One: September and October 1066
  King Amlaíb of Mumu was a happy man, to put it mildly. He found himself in
  arms with the young lad Murchad next to him, the younger knight spinning
  his newlywed around as the dance continued. 
  
  "It's honestly hard to believe that we are fully wed now," the joyful blonde
  said with a chuckle.

  "I know," came the reply along with a stolen kiss. Not that the other man
  minded.

  "They will want us to have an heir somehow, whether through adoption or - "

  "We will figure that out when the time comes," Amlaíb replied.

  "Many of the vassals seem to be -"

  "We will get there when we get there. For now, let's just enjoy tonight."

  "Indeed. I feel so very blessed to have you by my side."

  "I do too." Both men laughed, and the dance continued.

*** September 19, 1066
    "They will expect you to sire an heir at some point, Amlaíb," the
    golden knight chuckled as he pulled the heavy furs around the
    two. Yes, the night had been a long one, good for relaxing and
    ignoring the stresses of the time as the two snuggled close. 

    "I know that, dear husband, and I have already been in talks with
    one of my courtiers - Bébin. I think we had some ale together
    during our wedding.¨ 

    "Of course - you know she and I were friends," Murchad replied.

    "And she and I were as well."

*** October 3, 1066
    Amlaíb frowned as he heard his chancellor speaking. Of course the
    damned fool had let some bandits into the country, and now they
    would spread their disease and steal what they could, damn it. The
    councilor had been loyal to Conchobar, aye, but to Amlaíb? No
    sense of loyalty, and a sense of dread and almost hatred.

    "Councilor, I will need to speak with you after the meeting."

    "Of course, my liege."

    The meeting continued on - a young man had continued to offer to
    serve as physician, and so the king ultimately accepted the young
    man's offer /just/ so the lad would shut up about it.

    "You needed to speak with me, my king?" the man asked.

    "Yes. Unfortunately, your services are no longer required on the council."

    "Why?" the man asked, frowning.

    "You let bandits into the country despite them claiming to be
    merchants. Now, we have another situation to deal with. Your last
    act as councilor is to personally help me find the bandits and
    bring them to justice."

    The older man growled and stormed off, filled with rage.
