#+TITLE: Ashes
#+SUBTITLE: Book One of The Ashes Chronicles
#+author: Jacob Hilker
#+LaTeX_CLASS: novel
* Prologue
A sickening cough could be heard from the chambers of the old baron. One that was raw, and the air thick with the scent of illness and death. Inside, vassal knelt by lord's side, as Percy squeezed the hand of his old friend. The torches flickered, the small trails of smoke wisping into the air.

"Coelhelm, old friend," he softly said as tears began to form.

No response came from the lord, whose throat burned.

"I'm sorry that… that…" the Templar stuttered, he saw the last little bit of life fade from his lord's eyes.

He wept for his friend, his brother-in-arms during the war. His friend, whose wife he had buried after her childbirth ended in failure. Now who would rule the barony? Heahwald certainly was not fit to rule at all - too hedonistic and prideful to understand when he was wrong.

"The others need to know." He formed a cross on his chest, as Godric soon entered, embracing his friend.

"Percy... " he softly said, letting the elder sob softly into the tunic he wore.

"It would have happened at some point, and while I will weep for my brother, I know now he is in heaven with the saints, and that he is no longer suffering from the plague." He too sighed. "It is just unfortunate that…"

"I know, my lord. I know." Percy replied. "Heahwald is not going to be the right leader," he continued.

"I agree, but we have no other choice. No need for formalities, now, at least. All of us are in grief," Godric said as he wiped away a single tear. "May his soul be at rest now that he no longer suffers."

"Indeed, may his soul rest easy and may he not suffer any longer. Do we have another choice? I know Henry -"

"Right now, is not the best time to discuss the matter of who rules, Percival," Godric said.

"Apologies, m'lord."

"Your apology is accepted, and your concern is noted. Right now, unfortunately, it seems we have a funeral to prepare."

Outside, the winds of the approaching winter howled, as an icy chill ran down Percy's spine. The skies grew darker and cloudier as the sun faded beyond the horizon.

Outside the chamber, Heahwald frowned, pacing his own room. The torchlight flickered in the snowy night, and the old man shivered briefly.

'Why should my brother be the one with the throne simply because he is the older one by mere minutes? He has clearly proven that he is too trusting, too kind, and will never be strong against our enemies, wherever they may lay.


